version: '3.4'
services:
  db:
    container_name: mariadb
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_USER=milon27
      - MYSQL_PASSWORD=myPassWord
      - MYSQL_ROOT_PASSWORD=myPassWord
      - MYSQL_DATABASE=my_db
    ports:
      - 3307:3306
    volumes:
      - db_vol:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

#volumes(root label)
volumes:
  db_vol: {}
