import { PrismaClient, Gender } from '@prisma/client'

const prisma = new PrismaClient()

const countryList = [
    { name: 'Afghanistan', code: 'AF' },
    { name: 'Åland Islands', code: 'AX' },
    { name: 'Albania', code: 'AL' },
    { name: 'Algeria', code: 'DZ' },
    { name: 'American Samoa', code: 'AS' },
    { name: 'AndorrA', code: 'AD' },
    { name: 'Angola', code: 'AO' },
    { name: 'Anguilla', code: 'AI' },
    { name: 'Antarctica', code: 'AQ' },
    { name: 'Antigua and Barbuda', code: 'AG' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Armenia', code: 'AM' },
    { name: 'Aruba', code: 'AW' },
    { name: 'Australia', code: 'AU' },
    { name: 'Austria', code: 'AT' },
    { name: 'Azerbaijan', code: 'AZ' },
    { name: 'Bahamas', code: 'BS' },
    { name: 'Bahrain', code: 'BH' },
    { name: 'Bangladesh', code: 'BD' },
    { name: 'Barbados', code: 'BB' },
    { name: 'Belarus', code: 'BY' },
    { name: 'Belgium', code: 'BE' },
    { name: 'Belize', code: 'BZ' },
    { name: 'Benin', code: 'BJ' },
    { name: 'Bermuda', code: 'BM' },
    { name: 'Bhutan', code: 'BT' },
    { name: 'Bolivia', code: 'BO' },
    { name: 'Bosnia and Herzegovina', code: 'BA' },
    { name: 'Botswana', code: 'BW' },
    { name: 'Bouvet Island', code: 'BV' },
    { name: 'Brazil', code: 'BR' },
    { name: 'British Indian Ocean Territory', code: 'IO' },
    { name: 'Brunei Darussalam', code: 'BN' },
    { name: 'Bulgaria', code: 'BG' },
    { name: 'Burkina Faso', code: 'BF' },
    { name: 'Burundi', code: 'BI' },
    { name: 'Cambodia', code: 'KH' },
    { name: 'Cameroon', code: 'CM' },
    { name: 'Canada', code: 'CA' },
    { name: 'Cape Verde', code: 'CV' },
    { name: 'Cayman Islands', code: 'KY' },
    { name: 'Central African Republic', code: 'CF' },
    { name: 'Chad', code: 'TD' },
    { name: 'Chile', code: 'CL' },
    { name: 'China', code: 'CN' },
    { name: 'Christmas Island', code: 'CX' },
    { name: 'Cocos (Keeling) Islands', code: 'CC' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Comoros', code: 'KM' },
    { name: 'Congo', code: 'CG' },
    { name: 'Congo, The Democratic Republic of the', code: 'CD' },
    { name: 'Cook Islands', code: 'CK' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Cote D\'Ivoire', code: 'CI' },
    { name: 'Croatia', code: 'HR' },
    { name: 'Cuba', code: 'CU' },
    { name: 'Cyprus', code: 'CY' },
    { name: 'Czech Republic', code: 'CZ' },
    { name: 'Denmark', code: 'DK' },
    { name: 'Djibouti', code: 'DJ' },
    { name: 'Dominica', code: 'DM' },
    { name: 'Dominican Republic', code: 'DO' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Egypt', code: 'EG' },
    { name: 'El Salvador', code: 'SV' },
    { name: 'Equatorial Guinea', code: 'GQ' },
    { name: 'Eritrea', code: 'ER' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Ethiopia', code: 'ET' },
    { name: 'Falkland Islands (Malvinas)', code: 'FK' },
    { name: 'Faroe Islands', code: 'FO' },
    { name: 'Fiji', code: 'FJ' },
    { name: 'Finland', code: 'FI' },
    { name: 'France', code: 'FR' },
    { name: 'French Guiana', code: 'GF' },
    { name: 'French Polynesia', code: 'PF' },
    { name: 'French Southern Territories', code: 'TF' },
    { name: 'Gabon', code: 'GA' },
    { name: 'Gambia', code: 'GM' },
    { name: 'Georgia', code: 'GE' },
    { name: 'Germany', code: 'DE' },
    { name: 'Ghana', code: 'GH' },
    { name: 'Gibraltar', code: 'GI' },
    { name: 'Greece', code: 'GR' },
    { name: 'Greenland', code: 'GL' },
    { name: 'Grenada', code: 'GD' },
    { name: 'Guadeloupe', code: 'GP' },
    { name: 'Guam', code: 'GU' },
    { name: 'Guatemala', code: 'GT' },
    { name: 'Guernsey', code: 'GG' },
    { name: 'Guinea', code: 'GN' },
    { name: 'Guinea-Bissau', code: 'GW' },
    { name: 'Guyana', code: 'GY' },
    { name: 'Haiti', code: 'HT' },
    { name: 'Heard Island and Mcdonald Islands', code: 'HM' },
    { name: 'Holy See (Vatican City State)', code: 'VA' },
    { name: 'Honduras', code: 'HN' },
    { name: 'Hong Kong', code: 'HK' },
    { name: 'Hungary', code: 'HU' },
    { name: 'Iceland', code: 'IS' },
    { name: 'India', code: 'IN' },
    { name: 'Indonesia', code: 'ID' },
    { name: 'Iran, Islamic Republic Of', code: 'IR' },
    { name: 'Iraq', code: 'IQ' },
    { name: 'Ireland', code: 'IE' },
    { name: 'Isle of Man', code: 'IM' },
    { name: 'Israel', code: 'IL' },
    { name: 'Italy', code: 'IT' },
    { name: 'Jamaica', code: 'JM' },
    { name: 'Japan', code: 'JP' },
    { name: 'Jersey', code: 'JE' },
    { name: 'Jordan', code: 'JO' },
    { name: 'Kazakhstan', code: 'KZ' },
    { name: 'Kenya', code: 'KE' },
    { name: 'Kiribati', code: 'KI' },
    { name: 'Korea, Democratic People\'S Republic of', code: 'KP' },
    { name: 'Korea, Republic of', code: 'KR' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Kyrgyzstan', code: 'KG' },
    { name: 'Lao People\'S Democratic Republic', code: 'LA' },
    { name: 'Latvia', code: 'LV' },
    { name: 'Lebanon', code: 'LB' },
    { name: 'Lesotho', code: 'LS' },
    { name: 'Liberia', code: 'LR' },
    { name: 'Libyan Arab Jamahiriya', code: 'LY' },
    { name: 'Liechtenstein', code: 'LI' },
    { name: 'Lithuania', code: 'LT' },
    { name: 'Luxembourg', code: 'LU' },
    { name: 'Macao', code: 'MO' },
    { name: 'Macedonia, The Former Yugoslav Republic of', code: 'MK' },
    { name: 'Madagascar', code: 'MG' },
    { name: 'Malawi', code: 'MW' },
    { name: 'Malaysia', code: 'MY' },
    { name: 'Maldives', code: 'MV' },
    { name: 'Mali', code: 'ML' },
    { name: 'Malta', code: 'MT' },
    { name: 'Marshall Islands', code: 'MH' },
    { name: 'Martinique', code: 'MQ' },
    { name: 'Mauritania', code: 'MR' },
    { name: 'Mauritius', code: 'MU' },
    { name: 'Mayotte', code: 'YT' },
    { name: 'Mexico', code: 'MX' },
    { name: 'Micronesia, Federated States of', code: 'FM' },
    { name: 'Moldova, Republic of', code: 'MD' },
    { name: 'Monaco', code: 'MC' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'Montserrat', code: 'MS' },
    { name: 'Morocco', code: 'MA' },
    { name: 'Mozambique', code: 'MZ' },
    { name: 'Myanmar', code: 'MM' },
    { name: 'Namibia', code: 'NA' },
    { name: 'Nauru', code: 'NR' },
    { name: 'Nepal', code: 'NP' },
    { name: 'Netherlands', code: 'NL' },
    { name: 'Netherlands Antilles', code: 'AN' },
    { name: 'New Caledonia', code: 'NC' },
    { name: 'New Zealand', code: 'NZ' },
    { name: 'Nicaragua', code: 'NI' },
    { name: 'Niger', code: 'NE' },
    { name: 'Nigeria', code: 'NG' },
    { name: 'Niue', code: 'NU' },
    { name: 'Norfolk Island', code: 'NF' },
    { name: 'Northern Mariana Islands', code: 'MP' },
    { name: 'Norway', code: 'NO' },
    { name: 'Oman', code: 'OM' },
    { name: 'Pakistan', code: 'PK' },
    { name: 'Palau', code: 'PW' },
    { name: 'Palestinian Territory, Occupied', code: 'PS' },
    { name: 'Panama', code: 'PA' },
    { name: 'Papua New Guinea', code: 'PG' },
    { name: 'Paraguay', code: 'PY' },
    { name: 'Peru', code: 'PE' },
    { name: 'Philippines', code: 'PH' },
    { name: 'Pitcairn', code: 'PN' },
    { name: 'Poland', code: 'PL' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Puerto Rico', code: 'PR' },
    { name: 'Qatar', code: 'QA' },
    { name: 'Reunion', code: 'RE' },
    { name: 'Romania', code: 'RO' },
    { name: 'Russian Federation', code: 'RU' },
    { name: 'RWANDA', code: 'RW' },
    { name: 'Saint Helena', code: 'SH' },
    { name: 'Saint Kitts and Nevis', code: 'KN' },
    { name: 'Saint Lucia', code: 'LC' },
    { name: 'Saint Pierre and Miquelon', code: 'PM' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC' },
    { name: 'Samoa', code: 'WS' },
    { name: 'San Marino', code: 'SM' },
    { name: 'Sao Tome and Principe', code: 'ST' },
    { name: 'Saudi Arabia', code: 'SA' },
    { name: 'Senegal', code: 'SN' },
    { name: 'Serbia and Montenegro', code: 'CS' },
    { name: 'Seychelles', code: 'SC' },
    { name: 'Sierra Leone', code: 'SL' },
    { name: 'Singapore', code: 'SG' },
    { name: 'Slovakia', code: 'SK' },
    { name: 'Slovenia', code: 'SI' },
    { name: 'Solomon Islands', code: 'SB' },
    { name: 'Somalia', code: 'SO' },
    { name: 'South Africa', code: 'ZA' },
    { name: 'South Georgia and the South Sandwich Islands', code: 'GS' },
    { name: 'Spain', code: 'ES' },
    { name: 'Sri Lanka', code: 'LK' },
    { name: 'Sudan', code: 'SD' },
    { name: 'Suriname', code: 'SR' },
    { name: 'Svalbard and Jan Mayen', code: 'SJ' },
    { name: 'Swaziland', code: 'SZ' },
    { name: 'Sweden', code: 'SE' },
    { name: 'Switzerland', code: 'CH' },
    { name: 'Syrian Arab Republic', code: 'SY' },
    { name: 'Taiwan, Province of China', code: 'TW' },
    { name: 'Tajikistan', code: 'TJ' },
    { name: 'Tanzania, United Republic of', code: 'TZ' },
    { name: 'Thailand', code: 'TH' },
    { name: 'Timor-Leste', code: 'TL' },
    { name: 'Togo', code: 'TG' },
    { name: 'Tokelau', code: 'TK' },
    { name: 'Tonga', code: 'TO' },
    { name: 'Trinidad and Tobago', code: 'TT' },
    { name: 'Tunisia', code: 'TN' },
    { name: 'Turkey', code: 'TR' },
    { name: 'Turkmenistan', code: 'TM' },
    { name: 'Turks and Caicos Islands', code: 'TC' },
    { name: 'Tuvalu', code: 'TV' },
    { name: 'Uganda', code: 'UG' },
    { name: 'Ukraine', code: 'UA' },
    { name: 'United Arab Emirates', code: 'AE' },
    { name: 'United Kingdom', code: 'GB' },
    { name: 'United States', code: 'US' },
    { name: 'United States Minor Outlying Islands', code: 'UM' },
    { name: 'Uruguay', code: 'UY' },
    { name: 'Uzbekistan', code: 'UZ' },
    { name: 'Vanuatu', code: 'VU' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Viet Nam', code: 'VN' },
    { name: 'Virgin Islands, British', code: 'VG' },
    { name: 'Virgin Islands, U.S.', code: 'VI' },
    { name: 'Wallis and Futuna', code: 'WF' },
    { name: 'Western Sahara', code: 'EH' },
    { name: 'Yemen', code: 'YE' },
    { name: 'Zambia', code: 'ZM' },
    { name: 'Zimbabwe', code: 'ZW' }
]

const DeviceList = ["Apple", "Windows", "Android", "Linux"]
const GenderList = [Gender.MALE, Gender.FEMALE, Gender.OTHER]
const UTimeList = [62, 43, 64, 37, 39, 77, 1, 7, 56, 54, 61, 41, 24, 82, 95, 44, 90, 94, 75, 16, 69, 20, 88, 58, 52, 84, 68, 11, 3, 2, 13, 100, 15, 19, 78, 76, 30, 92, 22, 25, 59, 47, 89, 18, 67, 97, 27, 28, 46, 73, 35,
]


const getRandomIndex = (max: number) => {
    return Math.floor(Math.random() * (max - 0 + 1)) + 0;
}

const getCountry = () => {
    return countryList[getRandomIndex(countryList.length - 1)].code
}
const getGender = () => {
    return GenderList[getRandomIndex(GenderList.length - 1)]
}
const getDevice = () => {
    return DeviceList[getRandomIndex(DeviceList.length - 1)]
}
const getUtime = () => {
    return UTimeList[getRandomIndex(UTimeList.length - 1)]
}

const getRandomDate = () => {
    const date = new Date(new Date().getTime() - Math.random() * (1e+12))
    return date
}

const userList = [
    { "name": "Leanne Graham", "email": "Sincere@april.biz", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Ervin Howell", "email": "Shanna@melissa.tv", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Clementine Bauch", "email": "Nathan@yesenia.net", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Patricia Lebsack", "email": "Julianne.OConner@kory.org", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Chelsey Dietrich", "email": "Lucio_Hettinger@annie.ca", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Mrs. Dennis Schulist", "email": "Karley_Dach@jasper.info", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Kurtis Weissnat", "email": "Telly.Hoeger@billy.biz", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Nicholas Runolfsdottir V", "email": "Sherwood@rosamond.me", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Glenna Reichert", "email": "Chaim_McDermott@dana.io", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "Clementina DuBuque", "email": "Rey.Padberg@karina.biz", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sunt", "email": "quiaas@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "estdfsf@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ea", "email": "etdfs@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "eum", "email": "ullamdfs@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "nesciunt", "email": "repudiandaese@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dolorem", "email": "utewf@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "magnam", "email": "doloreewaew@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dolorem", "email": "dignissimosacea@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "nesciunt", "email": "consecteturewv@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "optio", "email": "quouyj@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "et", "email": "delectuserb@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "in", "email": "itaquerb@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dolorum", "email": "autdbfgs@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptatem", "email": "fugasvd@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "eveniet", "email": "reprehenderitxx@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sint", "email": "suscipit@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "fugit", "email": "eosxdd@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptate", "email": "evenietdsfd@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "adipisci", "email": "illumsfdsf@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "doloribus", "email": "quixxxxe3e@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "asperiores", "email": "repellat222@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dolor", "email": "eoscs@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "maxime", "email": "vscdseritatis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "autem", "email": "ensdvgsim@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "rem", "email": "ullagdgm@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "est", "email": "simdvilique@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "quasi", "email": "esdrfum@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "delectus", "email": "nfddon@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "iusto", "email": "odsfsdit@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "a", "email": "alisvsdas@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ullam", "email": "debitsis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "doloremque", "email": "desvserunt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "rerumsss@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "magnam", "email": "esvsda@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "id", "email": "nissvsdi@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "fuga", "email": "adsvdsv@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "provident", "email": "desvbitis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "explicabo", "email": "anisdvmi@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "eos", "email": "corsvdporis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "enim", "email": "usvrtet@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "non", "email": "molsdvestias@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "commodi", "email": "odsdvsio@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "eligendi", "email": "similsdique@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "optio", "email": "tesdvmporibus@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ut", "email": "estsvdw@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "aut", "email": "volusvhyptatem@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "quibusdam", "email": "savoluptatem@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ut", "email": "voluptdvates@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "laborum", "email": "insdvaventore@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "repellendus", "email": "errovar@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "soluta", "email": "savebunt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "iustvsvdo@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ut", "email": "minimsaea@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sit", "email": "totambra@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sit", "email": "debitibres@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "aaveraut@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sed", "email": "aabrnt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptatum", "email": "veveaniam@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "perspicavaiatis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "consequatur", "email": "aspvdsaeriores@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptatem", "email": "aabvab@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "beatae", "email": "eniavam@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptas", "email": "enimotnt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "et", "email": "iddys@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "consequatur", "email": "volsnytuptatibus@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "repudiandae", "email": "offsnticia@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "aliquid", "email": "represtnhenderit@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "odio", "email": "magnasntm@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "fugiat", "email": "offstniciis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "voluptatem", "email": "ssntunt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "et", "email": "occasntecati@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sint", "email": "quastnm@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "consequuntur", "email": "volusntptatem@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "enim", "email": "odistt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dignissimos", "email": "commonstdi@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "doloremque", "email": "sntsnut@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "necessitatibus", "email": "mosntsdi@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "quam", "email": "nostnsbis@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "pariatur", "email": "libersnto1@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "labore", "email": "sntsex@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "tempora", "email": "fasntscere@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "laudantium", "email": "ustnt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "odit", "email": "etnsnst@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "optio", "email": "sitnsntnt@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "dolore", "email": "sisntsmilique@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "placeat", "email": "qustnstasi@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "nostrum", "email": "esntsos@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sapiente", "email": "consstnsequatur@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "sint", "email": "resntpellat@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ad", "email": "minsntus@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "aut", "email": "libstnero@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "ratione", "email": "asntut@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "beatae", "email": "dosntlorem@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "qui", "email": "assntpernatur@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "id", "email": "earusntm@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "quaerat", "email": "instn@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "quas", "email": "eusnttsntm@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "laboriosam", "email": "dolorstnemque@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "temporibus", "email": "qusntntnjto@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() },
    { "name": "cupiditate", "email": "cupidsntitate@me.com", countryCode: getCountry(), device: getDevice(), gender: getGender(), usageTimeInMin: getUtime(), lastActive: getRandomDate() }
]

const doSeed = async () => {
    // clear seed
    await prisma.country.deleteMany()
    await prisma.users.deleteMany()
    //* create demo country
    await prisma.country.createMany({
        data: countryList
    })
    //* create demo users
    await prisma.users.createMany({
        data: userList
    })
}

doSeed().then(() => {
    console.log("seed done")
}).catch(e => {
    console.log("alredy seeded", e)
})